### ISSUE TITLE
How to translate country field

### ISSUE THREAD

**Issue by pedrofraile** [m-adamski/symfony-phone-number-bundle#1]
Hi!

I have just installed your package (great work BTW) and I am struggling to translate the country field to spanish, I see it uses the Intl component, but it shows the results in english, am I missing some configuration in order to change it to spanish?

Best regards.

Pedro.

**Comment by m-adamski** [comment]
Hi Pedro.

Sorry for my delayed response. Thank you!
I think that you have to set parameter locale in services.yaml file.

**Edit:**
Make sure you have the php-intl extension installed on your server.
